### ISSUE TITLE
Giffy Dialog ver updated bermalah Image widget tidak bisa di pakai

### ISSUE THREAD

**Issue by risnanto73** [risnanto73/covid-app#2]
Giffy Dialog ver updated bermalah Image widget tidak bisa di pakai

**Comment by M-Rifqy** [comment]
> Giffy Dialog ver updated bermalah Image widget tidak bisa di pakai

@risnanto73 skil isu

**Comment by risnanto73** [comment]
> > Giffy Dialog ver updated bermalah Image widget tidak bisa di pakai
> 
> @risnanto73 skil isu

kampret wehh emg lagi ada masalah itu versi 2.1

**Comment by risnanto73** [comment]
> > > Giffy Dialog ver updated bermalah Image widget tidak bisa di pakai
> > 
> > 
> > @risnanto73 skil isu
> 
> kampret wehh emg lagi ada masalah itu versi 2.1

@M-Rifqy downgrade pun ga mau

**Comment by risnanto73** [comment]
Makasih mase
